New version asdf+pipx, direnvrc_mac changed for that

diff --git a/direnvrc_mac b/direnvrc_mac
--- a/direnvrc_mac
+++ b/direnvrc_mac
@@ -19,9 +19,21 @@ use_asdf() {
   fi
 }
  
-asdf() {
-  unset asdf
-  asdf "$@"
+asdf_has() {
+  if [[ $# -lt 1 ]]; then
+    echo "ERROR: Wrong number of parameters, expected:" >&2
+    echo "       asdf_has [PLUGIN]" >&2
+    return 1
+  fi
+  local _plugin="$1"
+  if [[ -n "${ASDF_DATA_DIR}" ]] && [[ -d "${ASDF_DATA_DIR}/plugins/${_plugin}" ]]; then
+    return 0
+  elif [[ -d "${ASDF_DIR}/plugins/${_plugin}" ]]; then
+    return 0
+  elif [[ -d "${HOME}/.asdf/plugins/${_plugin}" ]]; then
+    return 0
+  fi
+  return 1
 }
  
 use_sdk() {
@@ -41,4 +53,66 @@ use_sdk() {
     echo "use sdk [CANDIDATE] [VERSION]" >&2
     return 1
   fi
+}
+ 
+realpath() {
+  [[ $1 == /* ]] && echo "$1" || echo "$PWD/${1#./}"
+}
+ 
+layout_python-venv() {
+  local python="${1:-python3}"
+  [[ $# -gt 0 ]] && shift
+  unset PYTHONHOME
+  if [[ -n "$VIRTUAL_ENV" ]]; then
+    VIRTUAL_ENV="$(realpath "${VIRTUAL_ENV}")"
+  else
+    local python_version
+    python_version="$("$python" -c "import platform; print(platform.python_version())")"
+    if [[ -z "$python_version" ]]; then
+      log_error "Could not detect Python version"
+      return 1
+    fi
+    VIRTUAL_ENV="$(direnv_layout_dir)/python-$python_version-venv"
+  fi
+  export VIRTUAL_ENV
+  if [[ ! -d "$VIRTUAL_ENV" ]]; then
+    log_status "no venv found; creating $VIRTUAL_ENV"
+    "$python" -m venv "$VIRTUAL_ENV"
+  fi
+ 
+  PATH_add "${VIRTUAL_ENV}/bin"
+}
+ 
+use_pre-commit() {
+  if ! [[ -f "$(git rev-parse --show-toplevel)/.git/hooks/pre-commit" ]]; then
+    pre-commit install --install-hooks
+  fi
+}
+ 
+use_pipx() {
+  if ! has python3; then
+    echo "Python 3 version 3.6 or higher required for PipX"
+    return 1
+  fi
+ 
+  if [[ -n "${VIRTUAL_ENV}" ]]; then
+    if ! python3 -m pip show -qq pipx; then
+      echo "Installing PipX into virtual env"
+      python3 -m pip install --upgrade pip setuptools pipx
+    fi
+  else
+    if ! has easy_install3; then
+      # `setuptools` is not a direct dependency of `pipx`, but it is required for correct operation
+      python3 -m pip install --user setuptools
+    fi
+    if ! has pipx; then
+      echo "Installing PipX for the current user"
+      python3 -m pip install --user pipx
+    fi
+  fi
+ 
+  # shellcheck disable=SC2155
+  export PIPX_HOME="$(direnv_layout_dir)/pipx"
+  export PIPX_BIN_DIR="${PIPX_HOME}/bin"
+  PATH_add "${PIPX_BIN_DIR}"
 }
